---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: books-app
  template:
    metadata:
      labels:
        app: books-app
    spec:
      containers:
      - name: books-container
        image: faalsh/books:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
---
apiVersion: v1
kind: Service 
metadata:
  name: books-svc
  labels:
    app: books-app
spec:
  selector:
    app: books-app
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80